/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAtividadesRouteImport } from './routes/_app/atividades'
import { Route as AppComprasRouteImport } from './routes/_app/compras'
import { Route as AppEstoqueRouteImport } from './routes/_app/estoque'
import { Route as AppMaisRouteImport } from './routes/_app/mais'
import { Route as AppPessoasRouteImport } from './routes/_app/pessoas'
import { Route as AppFrotaIndexRouteImport } from './routes/_app/frota/index'
import { Route as AppFrotaIdRouteImport } from './routes/_app/frota/$id'
import { Route as AppMaquinasIndexRouteImport } from './routes/_app/maquinas/index'
import { Route as AppMaquinasIdRouteImport } from './routes/_app/maquinas/$id'
import { Route as AppTalhoesIndexRouteImport } from './routes/_app/talhoes/index'
import { Route as AppTalhoesIdRouteImport } from './routes/_app/talhoes/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAtividadesRoute = AppAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AppRoute,
} as any)
const AppComprasRoute = AppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppMaisRoute = AppMaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => AppRoute,
} as any)
const AppPessoasRoute = AppPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaIndexRoute = AppFrotaIndexRouteImport.update({
  id: '/frota/',
  path: '/frota/',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaIdRoute = AppFrotaIdRouteImport.update({
  id: '/frota/$id',
  path: '/frota/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMaquinasIndexRoute = AppMaquinasIndexRouteImport.update({
  id: '/maquinas/',
  path: '/maquinas/',
  getParentRoute: () => AppRoute,
} as any)
const AppMaquinasIdRoute = AppMaquinasIdRouteImport.update({
  id: '/maquinas/$id',
  path: '/maquinas/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTalhoesIndexRoute = AppTalhoesIndexRouteImport.update({
  id: '/talhoes/',
  path: '/talhoes/',
  getParentRoute: () => AppRoute,
} as any)
const AppTalhoesIdRoute = AppTalhoesIdRouteImport.update({
  id: '/talhoes/$id',
  path: '/talhoes/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/atividades': typeof AppAtividadesRoute
  '/compras': typeof AppComprasRoute
  '/estoque': typeof AppEstoqueRoute
  '/mais': typeof AppMaisRoute
  '/pessoas': typeof AppPessoasRoute
  '/frota/$id': typeof AppFrotaIdRoute
  '/maquinas/$id': typeof AppMaquinasIdRoute
  '/talhoes/$id': typeof AppTalhoesIdRoute
  '/frota/': typeof AppFrotaIndexRoute
  '/maquinas/': typeof AppMaquinasIndexRoute
  '/talhoes/': typeof AppTalhoesIndexRoute
}
export interface FileRoutesByTo {
  '/atividades': typeof AppAtividadesRoute
  '/compras': typeof AppComprasRoute
  '/estoque': typeof AppEstoqueRoute
  '/mais': typeof AppMaisRoute
  '/pessoas': typeof AppPessoasRoute
  '/': typeof AppIndexRoute
  '/frota/$id': typeof AppFrotaIdRoute
  '/maquinas/$id': typeof AppMaquinasIdRoute
  '/talhoes/$id': typeof AppTalhoesIdRoute
  '/frota': typeof AppFrotaIndexRoute
  '/maquinas': typeof AppMaquinasIndexRoute
  '/talhoes': typeof AppTalhoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/atividades': typeof AppAtividadesRoute
  '/_app/compras': typeof AppComprasRoute
  '/_app/estoque': typeof AppEstoqueRoute
  '/_app/mais': typeof AppMaisRoute
  '/_app/pessoas': typeof AppPessoasRoute
  '/_app/': typeof AppIndexRoute
  '/_app/frota/$id': typeof AppFrotaIdRoute
  '/_app/maquinas/$id': typeof AppMaquinasIdRoute
  '/_app/talhoes/$id': typeof AppTalhoesIdRoute
  '/_app/frota/': typeof AppFrotaIndexRoute
  '/_app/maquinas/': typeof AppMaquinasIndexRoute
  '/_app/talhoes/': typeof AppTalhoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atividades'
    | '/compras'
    | '/estoque'
    | '/mais'
    | '/pessoas'
    | '/frota/$id'
    | '/maquinas/$id'
    | '/talhoes/$id'
    | '/frota/'
    | '/maquinas/'
    | '/talhoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/atividades'
    | '/compras'
    | '/estoque'
    | '/mais'
    | '/pessoas'
    | '/'
    | '/frota/$id'
    | '/maquinas/$id'
    | '/talhoes/$id'
    | '/frota'
    | '/maquinas'
    | '/talhoes'
  id:
    | '__root__'
    | '/_app'
    | '/_app/atividades'
    | '/_app/compras'
    | '/_app/estoque'
    | '/_app/mais'
    | '/_app/pessoas'
    | '/_app/'
    | '/_app/frota/$id'
    | '/_app/maquinas/$id'
    | '/_app/talhoes/$id'
    | '/_app/frota/'
    | '/_app/maquinas/'
    | '/_app/talhoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/atividades': {
      id: '/_app/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AppAtividadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compras': {
      id: '/_app/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AppComprasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque': {
      id: '/_app/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mais': {
      id: '/_app/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof AppMaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pessoas': {
      id: '/_app/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof AppPessoasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/frota/': {
      id: '/_app/frota/'
      path: '/frota'
      fullPath: '/frota/'
      preLoaderRoute: typeof AppFrotaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/frota/$id': {
      id: '/_app/frota/$id'
      path: '/frota/$id'
      fullPath: '/frota/$id'
      preLoaderRoute: typeof AppFrotaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maquinas/': {
      id: '/_app/maquinas/'
      path: '/maquinas'
      fullPath: '/maquinas/'
      preLoaderRoute: typeof AppMaquinasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maquinas/$id': {
      id: '/_app/maquinas/$id'
      path: '/maquinas/$id'
      fullPath: '/maquinas/$id'
      preLoaderRoute: typeof AppMaquinasIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/talhoes/': {
      id: '/_app/talhoes/'
      path: '/talhoes'
      fullPath: '/talhoes/'
      preLoaderRoute: typeof AppTalhoesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/talhoes/$id': {
      id: '/_app/talhoes/$id'
      path: '/talhoes/$id'
      fullPath: '/talhoes/$id'
      preLoaderRoute: typeof AppTalhoesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAtividadesRoute: typeof AppAtividadesRoute
  AppComprasRoute: typeof AppComprasRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppMaisRoute: typeof AppMaisRoute
  AppPessoasRoute: typeof AppPessoasRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFrotaIdRoute: typeof AppFrotaIdRoute
  AppMaquinasIdRoute: typeof AppMaquinasIdRoute
  AppTalhoesIdRoute: typeof AppTalhoesIdRoute
  AppFrotaIndexRoute: typeof AppFrotaIndexRoute
  AppMaquinasIndexRoute: typeof AppMaquinasIndexRoute
  AppTalhoesIndexRoute: typeof AppTalhoesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAtividadesRoute: AppAtividadesRoute,
  AppComprasRoute: AppComprasRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppMaisRoute: AppMaisRoute,
  AppPessoasRoute: AppPessoasRoute,
  AppIndexRoute: AppIndexRoute,
  AppFrotaIdRoute: AppFrotaIdRoute,
  AppMaquinasIdRoute: AppMaquinasIdRoute,
  AppTalhoesIdRoute: AppTalhoesIdRoute,
  AppFrotaIndexRoute: AppFrotaIndexRoute,
  AppMaquinasIndexRoute: AppMaquinasIndexRoute,
  AppTalhoesIndexRoute: AppTalhoesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
